"""Pollen Region Mapping für GeoWeather."""

POLLEN_REGION_MAPPING = {
    "Ahrweiler": 102,
    "Aichach-Friedberg": 123,
    "Alb-Donau-Kreis": 113,
    "Alb-Donau-Kreis und Stadt Ulm": 113,
    "Altenkirchen (Westerwald)": 102,
    "Altötting": 123,
    "Alzey-Worms": 101,
    "Amberg": 123,
    "Amberg-Sulzbach": 123,
    "Ammerland": 32,
    "Ansbach": 123,
    "Aschaffenburg": 124,
    "Augsburg": 123,
    "Aurich": 32,
    "Aurich - Binnenland": 32,
    "Aurich - Küste": 32,
    "Baden-Baden": 112,
    "Bad Dürkheim": 102,
    "Bad Kissingen": 123,
    "Bad Kreuznach": 102,
    "Bad Tölz-Wolfratshausen": 123,
    "Bamberg": 124,
    "Bautzen": 82,
    "Bautzen - Bergland": 82,
    "Bautzen - Tiefland": 81,
    "Bayreuth": 123,
    "Berchtesgadener Land": 123,
    "Bergisches Land": 43,
    "Bergstraße": 91,
    "Berlin": 50,
    "Berlin-Mitte": 50,
    "Bernkastel-Wittlich": 102,
    "Biberach": 112,
    "Bielefeld": 42,
    "Birkenfeld": 102,
    "Bochum": 43,
    "Bodenseekreis": 112,
    "Bonn": 41,
    "Borken": 43,
    "Bottrop": 43,
    "Brandenburg und Berlin": 50,
    "Braunschweig": 32,
    "Breisgau-Hochschwarzwald": 112,
    "Bremen": 31,
    "Bremerhaven": 32,
    "Böblingen": 112,
    "Calw": 112,
    "Celle": 32,
    "Cham": 123,
    "Cloppenburg": 32,
    "Coburg": 123,
    "Cochem-Zell": 102,
    "Coesfeld": 43,
    "Cuxhaven": 32,
    "Cuxhaven - Binnenland": 32,
    "Cuxhaven - Küste": 32,
    "Dachau": 123,
    "Darmstadt": 92,
    "Darmstadt-Dieburg": 92,
    "Deggendorf": 122,
    "Delmenhorst": 32,
    "Diepholz": 32,
    "Dillingen a.d. Donau": 122,
    "Dingolfing-Landau": 123,
    "Dithmarschen": 12,
    "Dithmarschen - Binnenland": 12,
    "Dithmarschen - Küste": 12,
    "Donau-Ries": 122,
    "Donnersbergkreis": 102,
    "Dortmund": 43,
    "Duisburg": 41,
    "Düsseldorf": 41,
    "Düren": 43,
    "Dresden": 81,
    "Dresden-Altstadt": 81,
    "Dresden-Neustadt": 81,
    "Ebersberg": 123,
    "Eichstätt": 123,
    "Eifel": 102,
    "Eifelkreis Bitburg-Prüm": 102,
    "Elbe-Weser-Gebiet": 32,
    "Emden": 32,
    "Emmendingen": 112,
    "Emsland": 31,
    "Ennepe-Ruhr-Kreis": 43,
    "Enzkreis": 112,
    "Enzkreis und Stadt Pforzheim": 112,
    "Erding": 123,
    "Erlangen": 123,
    "Erlangen-Höchstadt": 123,
    "Essen": 41,
    "Esslingen": 112,
    "Euskirchen": 43,
    "Flensburg": 12,
    "Forchheim": 123,
    "Frankenthal (Pfalz)": 101,
    "Frankfurt am Main": 92,
    "Freiburg im Breisgau": 112,
    "Freising": 123,
    "Freudenstadt": 112,
    "Freyung-Grafenau": 123,
    "Friesland": 31,
    "Friesland - Binnenland": 31,
    "Friesland - Küste": 31,
    "Fulda": 91,
    "Fürstenfeldbruck": 123,
    "Fürth": 123,
    "Garmisch-Partenkirchen": 123,
    "Gelsenkirchen": 43,
    "Germersheim": 102,
    "Gießen": 91,
    "Gifhorn": 32,
    "Goslar": 32,
    "Görlitz": 82,
    "Görlitz - Bergland": 82,
    "Görlitz - Tiefland": 81,
    "Grafschaft Bentheim": 31,
    "Groß-Gerau": 92,
    "Göttingen": 32,
    "Günzburg": 123,
    "Gütersloh": 42,
    "Göppingen": 112,
    "Haarstrang": 43,
    "Hagen": 43,
    "Hamburg": 12,
    "Hameln-Pyrmont": 32,
    "Hamm": 43,
    "Harburg": 32,
    "Harz": 32,
    "Harz - Bergland (Oberharz)": 62,
    "Harz - Tiefland": 62,
    "Haßberge": 123,
    "Heidelberg": 111,
    "Heidekreis": 32,
    "Heidenheim": 112,
    "Heilbronn": 111,
    "Heinsberg": 43,
    "Helmstedt": 32,
    "Herford": 43,
    "Herne": 43,
    "Hersfeld-Rotenburg": 91,
    "Herzogtum Lauenburg": 12,
    "Hildesheim": 32,
    "Hochsauerlandkreis": 43,
    "Hochtaunuskreis": 91,
    "Hof": 123,
    "Hohenlohekreis": 112,
    "Holzminden": 32,
    "Hunsrück-Mosel": 101,
    "Höxter": 42,
    "Ingolstadt": 123,
    "Insel Borkum": 32,
    "Insel Helgoland": 11,
    "Kaiserslautern": 102,
    "Karlsruhe": 111,
    "Kassel": 91,
    "Kaufbeuren": 123,
    "Kelheim": 123,
    "Kempten (Allgäu)": 121,
    "Kiel": 12,
    "Kinzig-Region": 91,
    "Kitzingen": 124,
    "Kleve": 43,
    "Koblenz": 102,
    "Konstanz": 112,
    "Krefeld": 43,
    "Kreis Breisgau-Hochschwarzwald und Stadt Freiburg": 112,
    "Kreis Darmstadt-Dieburg und Stadt Darmstadt": 92,
    "Kreis Mainz-Bingen und Stadt Mainz": 101,
    "Kreis Straubing-Bogen und Stadt Straubing": 122,
    "Kreis Südwestpfalz und Stadt Pirmasens": 102,
    "Kreis Trier-Saarburg und Stadt Trier": 102,
    "Kreis und Stadt Ansbach": 123,
    "Kreis und Stadt Aschaffenburg": 124,
    "Kreis und Stadt Augsburg": 123,
    "Kreis und Stadt Bamberg": 124,
    "Kreis und Stadt Bayreuth": 123,
    "Kreis und Stadt Coburg": 123,
    "Kreis und Stadt Fürth": 123,
    "Kreis und Stadt Heilbronn": 111,
    "Kreis und Stadt Hof": 123,
    "Kreis und Stadt Kaiserslautern": 102,
    "Kreis und Stadt Karlsruhe": 111,
    "Kreis und Stadt Kassel": 91,
    "Kreis und Stadt Landshut": 123,
    "Kreis und Stadt München": 121,
    "Kreis und Stadt Offenbach": 92,
    "Kreis und Stadt Oldenburg": 31,
    "Kreis und Stadt Osnabrück": 31,
    "Kreis und Stadt Passau": 122,
    "Kreis und Stadt Regensburg": 123,
    "Kreis und Stadt Rosenheim": 123,
    "Kreis und Stadt Schweinfurt": 124,
    "Kreis und Stadt Würzburg": 124,
    "Kronach": 123,
    "Kulmbach": 123,
    "Kusel": 102,
    "Köln": 41,
    "Köln-Niederrheinische Bucht": 41,
    "Lahn-Dill-Kreis": 91,
    "Landau in der Pfalz": 101,
    "Landkreis Kitzingen": 124,
    "Landsberg am Lech": 123,
    "Landshut": 123,
    "Leer": 32,
    "Leer (ohne Borkum)": 32,
    "Leipzig": 81,
    "Leverkusen": 43,
    "Lichtenfels": 123,
    "Limburg-Weilburg": 91,
    "Lindau (Bodensee)": 123,
    "Lippe": 42,
    "Ludwigsburg": 112,
    "Ludwigshafen am Rhein": 101,
    "Ludwigslust-Parchim": 20,
    "Ludwigslust-Parchim - Ost": 20,
    "Ludwigslust-Parchim - West": 20,
    "Lübeck": 12,
    "Lüchow-Dannenberg": 32,
    "Lüneburg": 32,
    "Lörrach": 112,
    "Main-Kinzig-Kreis": 92,
    "Main-Spessart": 123,
    "Main-Tauber-Kreis": 112,
    "Main-Taunus-Kreis": 92,
    "Mainz": 101,
    "Mainz-Bingen": 101,
    "Mannheim": 111,
    "Marburg-Biedenkopf": 91,
    "Mayen-Koblenz": 102,
    "Mecklenburgische Seenplatte": 20,
    "Mecklenburgische Seenplatte - Nord": 20,
    "Mecklenburgische Seenplatte - Südost": 20,
    "Mecklenburgische Seenplatte - West": 20,
    "Memmingen": 123,
    "Mettmann": 41,
    "Miesbach": 123,
    "Miltenberg": 123,
    "Minden-Lübbecke": 43,
    "Mittelhessen": 91,
    "Mittelsachsen": 81,
    "Mittelsachsen - Bergland": 82,
    "Mittelsachsen - Tiefland": 81,
    "Mönchengladbach": 43,
    "Mülheim an der Ruhr": 43,
    "Mühldorf a. Inn": 123,
    "München": 121,
    "Münster": 42,
    "Märkischer Kreis": 43,
    "Neckar-Odenwald-Kreis": 112,
    "Neu-Ulm": 123,
    "Neuburg-Schrobenhausen": 123,
    "Neumarkt i.d. OPf.": 123,
    "Neumünster": 12,
    "Neustadt a.d. Aisch-Bad Windsheim": 123,
    "Neustadt a.d. Waldnaab": 123,
    "Neustadt an der Weinstraße": 102,
    "Neuwied": 102,
    "Niederrhein": 43,
    "Niedersachsen - Küste": 32,
    "Niedersachsen - nördlich der Aller": 32,
    "Niedersachsen - südlich der Aller": 32,
    "Nienburg (Weser)": 32,
    "Nordfriesland": 12,
    "Nordfriesland - Binnenland": 12,
    "Nordfriesland - Küste": 12,
    "Nordhessen": 91,
    "Nordosthessen": 91,
    "Nordsachsen": 81,
    "Nordsachsen - Nord": 81,
    "Nordsachsen - Süd": 81,
    "Nordwestmecklenburg": 20,
    "Nordwestmecklenburg - Binnenland": 20,
    "Nordwestmecklenburg - Küste": 20,
    "Northeim": 32,
    "Nürnberg": 123,
    "Nürnberger Land": 123,
    "Nördliches Rheinland-Pfalz": 101,
    "Nördliches Weserbergland": 43,
    "Oberallgäu": 123,
    "Oberbergischer Kreis": 43,
    "Oberhausen": 43,
    "Odenwald/Bergstraße": 91,
    "Odenwaldkreis": 91,
    "Offenbach": 92,
    "Offenbach am Main": 92,
    "Oldenburg": 31,
    "Oldenburg (Oldb)": 31,
    "Olpe": 43,
    "Ortenaukreis": 112,
    "Osnabrück": 31,
    "Osnabrücker Raum": 31,
    "Ostallgäu": 123,
    "Ostalbkreis": 112,
    "Osterholz": 32,
    "Ostholstein": 12,
    "Ostholstein - Binnenland": 12,
    "Ostholstein - Küste": 12,
    "Paderborn": 42,
    "Passau": 122,
    "Peine": 32,
    "Pfaffenhofen a.d. Ilm": 123,
    "Pforzheim": 112,
    "Pinneberg": 12,
    "Pinneberg (ohne Helgoland)": 12,
    "Pirmasens": 102,
    "Plön": 12,
    "Plön - Binnenland": 12,
    "Plön - Küste": 12,
    "Rastatt": 112,
    "Ravensburg": 112,
    "Recklinghausen": 43,
    "Regen": 123,
    "Regensburg": 123,
    "Region Hannover": 32,
    "Rems-Murr-Kreis": 112,
    "Remscheid": 43,
    "Rendsburg-Eckernförde": 12,
    "Rendsburg-Eckernförde - Binnenland": 12,
    "Rendsburg-Eckernförde - Küste": 12,
    "Reutlingen": 112,
    "Rhein-Erft-Kreis": 41,
    "Rhein-Hunsrück-Kreis": 101,
    "Rhein-Kreis Neuss": 41,
    "Rhein-Lahn-Kreis": 101,
    "Rhein-Main-Gebiet": 92,
    "Rhein-Neckar-Kreis": 111,
    "Rhein-Neckar-Kreis und Stadt Heidelberg": 111,
    "Rhein-Pfalz-Kreis": 101,
    "Rhein-Pfalz-Kreis und Stadt Ludwigshafen": 101,
    "Rhein-Sieg-Kreis": 41,
    "Rhein-Sieg Kreis": 41,
    "Rheinhessen": 101,
    "Rheingau-Taunus-Kreis": 91,
    "Rheinisch-Bergischer Kreis": 41,
    "Rhön": 91,
    "Rhön-Grabfeld": 123,
    "Rosenheim": 123,
    "Rostock": 20,
    "Rostock - Binnenland Nord": 20,
    "Rostock - Binnenland Süd": 20,
    "Rostock - Küste": 20,
    "Rotenburg (Wümme)": 32,
    "Roth": 123,
    "Rottal-Inn": 123,
    "Rottweil": 112,
    "Rottweil - Bergland": 112,
    "Saar-Region": 103,
    "Salzgitter": 32,
    "Sauerland": 43,
    "Schaumburg": 32,
    "Schleswig-Flensburg": 12,
    "Schleswig-Flensburg - Binnenland": 12,
    "Schleswig-Flensburg - Küste": 12,
    "Schleswig-Holstein - Binnenland": 12,
    "Schleswig-Holstein - Helgoland": 12,
    "Schleswig-Holstein - Küste (Nordsee)": 11,
    "Schleswig-Holstein - Küste (Ostsee)": 12,
    "Schwabach": 123,
    "Schwandorf": 123,
    "Schwalm-Eder-Kreis": 91,
    "Schwarzwald-Baar-Kreis": 113,
    "Schwäbisch Hall": 112,
    "Schweinfurt": 124,
    "Segeberg": 12,
    "Siegen-Wittgenstein": 43,
    "Sigmaringen": 112,
    "Soest": 43,
    "Solingen": 43,
    "Speyer": 102,
    "Stade": 32,
    "Starnberg": 121,
    "Steinburg": 12,
    "Steinfurt": 43,
    "Stormarn": 12,
    "Straubing": 122,
    "Straubing-Bogen": 122,
    "Stuttgart": 111,
    "StädteRegion Aachen": 41,
    "Sächsische Schweiz-Osterzgebirge": 82,
    "Sächsische Schweiz-Osterzgebirge - Tiefland": 81,
    "Sächsische Schweiz-Osterzgebirge - ostelbisches Bergland": 82,
    "Sächsische Schweiz-Osterzgebirge - westelbisches Bergland": 82,
    "Südliche Weinstraße": 102,
    "Südliches Rheinland-Pfalz": 101,
    "Südliches Weserbergland": 43,
    "Südwestpfalz": 102,
    "Taunus": 91,
    "Tirschenreuth": 123,
    "Traunstein": 121,
    "Trier": 102,
    "Trier-Saarburg": 102,
    "Tuttlingen": 112,
    "Tübingen": 112,
    "Uelzen": 32,
    "Ulm": 112,
    "Unna": 43,
    "Unterallgäu": 123,
    "Vechta": 32,
    "Verden": 32,
    "Viersen": 43,
    "Vogelsbergkreis": 91,
    "Vogtlandkreis": 82,
    "Vogtlandkreis - Bergland": 82,
    "Vogtlandkreis - Tiefland": 82,
    "Vorpommern-Greifswald": 20,
    "Vorpommern-Greifswald - Binnenland Nord": 20,
    "Vorpommern-Greifswald - Binnenland Süd": 20,
    "Vorpommern-Greifswald - Küste Nord": 20,
    "Vorpommern-Greifswald - Küste Süd": 20,
    "Vorpommern-Rügen": 20,
    "Vorpommern-Rügen - Binnenland": 20,
    "Vorpommern-Rügen - Insel Rügen": 20,
    "Vorpommern-Rügen - Küste": 20,
    "Vulkaneifel": 102,
    "Waldeck-Frankenberg": 91,
    "Waldshut": 112,
    "Warendorf": 43,
    "Weiden i.d. OPf.": 123,
    "Weilheim-Schongau": 123,
    "Weißenburg-Gunzenhausen": 123,
    "Werra-Meißner-Kreis": 91,
    "Wesel": 43,
    "Weser-Ems-Gebiet": 31,
    "Weser-Leine-Bergland": 32,
    "Wesermarsch": 32,
    "Wesermarsch - Binnenland": 32,
    "Wesermarsch - Küste": 32,
    "Westerwald/Biedenkopf": 91,
    "Westerwaldkreis": 102,
    "Westliches Münsterland": 42,
    "Westliches Ruhrgebiet": 43,
    "Wetteraukreis": 91,
    "Wiesbaden": 92,
    "Wilhelmshaven": 32,
    "Wittmund": 32,
    "Wittmund - Binnenland": 32,
    "Wittmund - Küste": 32,
    "Wolfenbüttel": 32,
    "Wolfsburg": 32,
    "Worms": 101,
    "Wunsiedel i. Fichtelgebirge": 123,
    "Wuppertal": 43,
    "Würzburg": 124,
    "Zollernalbkreis": 113,
    "Zweibrücken": 102,
    "Zwickau": 81,
    "Zwickau - Bergland": 82,
    "Zwickau - Tiefland": 81,
    "Östliches Münsterland": 42,
    "Östliches Ruhrgebiet": 43,
}
